<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LotRequest;
use Carbon\Carbon;

class LotRequestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $requests = [
            [
                'request_no' => '260222083000',
                'mc_no' => 'EQP-A101',
                'line' => 'Line A',
                'area' => 'A1',
                'requestor' => 'John Smith',
                'lot_no' => 'LOT-2026-001',
                'model' => 'Model A',
                'quantity' => 25,
                'lipas' => 'N',
                'lot_tat' => '2h',
                'requested' => Carbon::now()->subHours(2)->subMinutes(15),
                'completed' => null,
                'response_time' => null,
                'response_by' => null,
                'status' => 'PENDING',
                'remarks' => 'High priority customer order',
            ],
            [
                'request_no' => '260222071500',
                'mc_no' => 'EQP-A102',
                'line' => 'Line B',
                'area' => 'A2',
                'requestor' => 'Maria Garcia',
                'lot_no' => 'LOT-2026-002',
                'model' => 'Model B',
                'quantity' => 50,
                'lipas' => 'Y',
                'lot_tat' => '3h',
                'requested' => Carbon::now()->subHours(5)->subMinutes(30),
                'completed' => Carbon::now()->subHours(3),
                'response_time' => '2h 30m',
                'response_by' => 'Admin User',
                'status' => 'COMPLETED',
                'remarks' => 'Standard processing',
            ],
            [
                'request_no' => '260221142000',
                'mc_no' => 'EQP-B205',
                'line' => 'Line C',
                'area' => 'A3',
                'requestor' => 'David Chen',
                'lot_no' => 'LOT-2026-003',
                'model' => 'Model C',
                'quantity' => 30,
                'lipas' => 'Y',
                'lot_tat' => '4h',
                'requested' => Carbon::now()->subDay()->subHours(9)->subMinutes(40),
                'completed' => Carbon::now()->subDay()->addHours(10)->addMinutes(15),
                'response_time' => '19h 55m',
                'response_by' => 'Admin User',
                'status' => 'COMPLETED',
                'remarks' => 'Completed ahead of schedule',
            ],
            [
                'request_no' => '260222060000',
                'mc_no' => 'EQP-C310',
                'line' => 'Line D',
                'area' => 'A1',
                'requestor' => 'Sarah Johnson',
                'lot_no' => 'LOT-2026-004',
                'model' => 'Model A',
                'quantity' => 40,
                'lipas' => 'N',
                'lot_tat' => '5h',
                'requested' => Carbon::now()->subHours(4)->subMinutes(45),
                'completed' => null,
                'response_time' => null,
                'response_by' => null,
                'status' => 'PENDING',
                'remarks' => 'Regular order',
            ],
            [
                'request_no' => '260222090000',
                'mc_no' => 'EQP-A103',
                'line' => 'Line E',
                'area' => 'A2',
                'requestor' => 'Michael Brown',
                'lot_no' => 'LOT-2026-005',
                'model' => 'Model D',
                'quantity' => 35,
                'lipas' => 'N',
                'lot_tat' => '2h',
                'requested' => Carbon::now()->subHours(1)->subMinutes(45),
                'completed' => null,
                'response_time' => null,
                'response_by' => null,
                'status' => 'REJECTED',
                'remarks' => 'Expedite processing',
            ],
            [
                'request_no' => '260221103000',
                'mc_no' => 'EQP-A104',
                'line' => 'Line F',
                'area' => 'A3',
                'requestor' => 'Emily Davis',
                'lot_no' => 'LOT-2026-006',
                'model' => 'Model B',
                'quantity' => 45,
                'lipas' => 'Y',
                'lot_tat' => '6h',
                'requested' => Carbon::now()->subDay()->subHours(13)->subMinutes(30),
                'completed' => Carbon::now()->subHours(16)->subMinutes(15),
                'response_time' => '21h 15m',
                'response_by' => 'Admin User',
                'status' => 'COMPLETED',
                'remarks' => 'Batch processing',
            ],
            [
                'request_no' => '260222100000',
                'mc_no' => 'EQP-D401',
                'line' => 'Line G',
                'area' => 'A1',
                'requestor' => 'Robert Wilson',
                'lot_no' => 'LOT-2026-007',
                'model' => 'Model E',
                'quantity' => 20,
                'lipas' => 'N',
                'lot_tat' => '3h',
                'requested' => Carbon::now()->subMinutes(45),
                'completed' => null,
                'response_time' => null,
                'response_by' => null,
                'status' => 'PENDING',
                'remarks' => 'Urgent request',
            ],
            [
                'request_no' => '260222053000',
                'mc_no' => 'EQP-E502',
                'line' => 'Line H',
                'area' => 'A2',
                'requestor' => 'Lisa Anderson',
                'lot_no' => 'LOT-2026-008',
                'model' => 'Model F',
                'quantity' => 55,
                'lipas' => 'Y',
                'lot_tat' => '4h',
                'requested' => Carbon::now()->subHours(5)->subMinutes(30),
                'completed' => Carbon::now()->subHours(2),
                'response_time' => '3h 30m',
                'response_by' => 'Admin User',
                'status' => 'COMPLETED',
                'remarks' => 'Quality check passed',
            ],
            [
                'request_no' => '260222073000',
                'mc_no' => 'EQP-F603',
                'line' => 'Line I',
                'area' => 'A3',
                'requestor' => 'James Martinez',
                'lot_no' => 'LOT-2026-009',
                'model' => 'Model G',
                'quantity' => 28,
                'lipas' => 'N',
                'lot_tat' => '2h',
                'requested' => Carbon::now()->subHours(3)->subMinutes(30),
                'completed' => null,
                'response_time' => null,
                'response_by' => null,
                'status' => 'CANCELLED',
                'remarks' => 'In production',
            ],
            [
                'request_no' => '260221160000',
                'mc_no' => 'EQP-G704',
                'line' => 'Line J',
                'area' => 'A1',
                'requestor' => 'Patricia Taylor',
                'lot_no' => 'LOT-2026-010',
                'model' => 'Model H',
                'quantity' => 32,
                'lipas' => 'Y',
                'lot_tat' => '5h',
                'requested' => Carbon::now()->subDay()->subHours(8),
                'completed' => Carbon::now()->subDay()->subHours(2)->subMinutes(30),
                'response_time' => '5h 30m',
                'response_by' => 'Admin User',
                'status' => 'COMPLETED',
                'remarks' => 'Completed on time',
            ],
        ];

        foreach ($requests as $request) {
            LotRequest::create($request);
        }

        $this->command->info('Lot requests seeded successfully!');
    }
}
